---
- name: Set variable for conditional check
  set_fact:
    current_env: "{{item['environments'] | map(attribute='name') | join(',')}}"
- name: show environment variable
  debug:
    msg: "{{current_env}}"
- name: Promote the new content view version
  redhat.satellite.content_view_version:
    username: "{{ sat_publisher_username }}"
    password: "{{ sat_publisher_password }}"
    server_url: "{{ sat_server_url }}"
    organization: "{{ sat_organization }}"
    validate_certs: "{{ sat_validate_certs }}"
    content_view: "{{ item['content_view']['name']}}"
    description: "{{ description }}"
    lifecycle_environments: "CBS-Production"
    version: "{{item.version}}"
  when: current_env == "Pre-production"
...
