---
- name: Publish a content
  hosts: localhost
  connection: local
  tasks:
  - name: "Show a content view version"
    redhat.satellite.content_view_version_info:
      username: "admin"
      password: "it22"
      server_url: "https://cbs-satellite-master.it22.cloud"
      content_view: "CBS-content-views"
      organization: "IT22"
      search: 'version = "1.0"'
    register: task1
  - name: Debug and print
    debug:
      msg: "{{task1}}"
  
  - name: "Show all content view_versions for a content view"
    redhat.satellite.content_view_version_info:
      username: "admin"
      password: "it22"
      server_url: "https://cbs-satellite-master.it22.cloud"
      organization: "IT22"
      content_view: "CBS-content-views"
      search: 'environments: "CBS-production"'
    register: task2
  - name: Debug and print
    debug:
      msg: "{{task2}}"
...