---
# This play uses the joblauncher role to launch monthly jobs on Satellite

- name: Launches jobs on Satellite
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Set the list of monthly jobs as the job list
      set_fact: 
        job_list: "{{ jobs_monthly }}"
  roles:
    - joblauncher
...     
