---
- name: Publish a content
  hosts: localhost
  connection: local
  tasks:
  - name: "Publish a content view and promote that version to Pre-prod & CBS-Prod, not idempotent"
    redhat.satellite.content_view_version:
      username: "admin"
      password: "it22"
      server_url: "https://cbs-satellite-master.it22.cloud"
      content_view: "CBS-content-views"
      organization: "IT22"
      #current_lifecycle_environment: "Pre-production"
      lifecycle_environments: "Pre-production"
      version: "3.0"
...