---
- name: Publish a content
  hosts: localhost
  connection: local
  tasks:
  - name: Show all content view_versions for a content view
    redhat.satellite.content_view_version_info:
      username: "{{ sat_publisher_username }}"
      password: "{{ sat_publisher_password }}"
      organization: "{{ sat_organization }}"
      server_url: "{{ sat_server_url }}"
      content_view: "CBS-content-views"
      validate_certs: "{{ sat_validate_certs }}"
    register: version_info

  - name: Flatten list
    set_fact:
      flat_version_info: "{{version_info['content_view_versions'] | flatten}}"
  
  - name: Set variable and promote content
    include_tasks: supplemental_pc.yml
    loop: "{{ flat_version_info | default([], true) }}"

#  - name: debug extravaganza
#    debug:
#      msg: "{{item.version}}" 
#    loop: "{{flat_version_info}}"
...
