---
- name: Content CBS promotion
  hosts: localhost
  connection: local
  tasks:
    - name: Show all content view_versions for a content view
      redhat.satellite.content_view_version_info:
        username: "{{ sat_publisher_username }}"
        password: "{{ sat_publisher_password }}"
        organization: "{{ sat_organization }}"
        server_url: "{{ sat_server_url }}"
        content_view: "CBS-content-views"
        validate_certs: no
        search: 'name = "CBS-Production"'
      register: version_info
    - name: debug value
      debug:
        msg: "{{version_info}}"
...
