---
- name: Content CBS promotion
  hosts: localhost
  connection: local
  tasks:
    - name: Show all content view_versions for a content view
      redhat.satellite.content_view_version_info:
        username: "{{ sat_publisher_username }}"
        password: "{{ sat_publisher_password }}"
        organization: "{{ sat_organization }}"
        server_url: "{{ sat_server_url }}"
        content_view: "CBS-content-views"
        validate_certs: "{{ sat_validate_certs }}"
      register: version_info

    - name: Flatten list
      set_fact:
        flat_version_info: "{{version_info['content_view_versions'] | flatten}}"
    
    - name: debug value
      debug:
        msg: "{{item.version}}  {{item.environments | map(attribute='name') }}"
      loop: "{{flat_version_info }}"

...
