# This play removes the unused contentviews for the Satellite
# The only contentviews that will remain are the contentviews in production and in pre-production
#
# Get complete information on CV
- name: Get contentview information
  redhat.satellite.content_view_info:
    username: "{{ sat_publisher_username }}"
    password: "{{ sat_publisher_password }}"
    server_url: "{{ sat_server_url }}"
    validate_certs: "{{ sat_validate_certs }}"
    name: "{{ cv_name }}"
  register: cvs_list

# Compose a list of CV versions that are not used in an environment
- name: Compose version list
  set_fact:
    cvv_remove_list: "{{ cvv_remove_list }} + ['{{ item['version'] }}']"
  loop: "{{ cvs_list['content_view']['versions'] }}"
  when: item['environment_ids'] == []

# Removes all the CV version that are on the list of CV versions to remove
- name: Remove CV versions
  redhat.satellite.content_view_version:
    username: "{{ sat_publisher_username }}"
    password: "{{ sat_publisher_password }}"
    server_url: "{{ sat_server_url }}"
    organization: "{{ sat_organization }}"
    validate_certs: "{{ sat_validate_certs }}"
    content_view: "{{ cv_name }}"
    state: absent
    version: "{{ item }}"
  loop: "{{ cvv_remove_list }}"
...  
